app:
  env: "dev"
  timezone: "Europe/Moscow"

telegram:
  token: "${TELEGRAM_TOKEN}"
  admin_chat_id: 439480376,1041899019
  request_timeout_sec: 30

http:
  addr: ":8080"

payments:
  base_url: "https://example.com"

postgres:
  dsn: "postgres://postgres:postgres@127.0.0.1:5433/postgres?sslmode=disable"

metrics:
  enabled: true
